

build:
	go build -race -o ./bin/control_errors ./cmd/client/main.go

tidy:
	go mod tidy

clean:
	rm -rf bin/control_errors

download:
	go mod download

release:
	env GOOS=linux GOARCH=amd64 go build -o ./bin/canary-linux ./cmd/client

package-deb:
	env GOOS=linux GOARCH=amd64 go build -o ./bin/canary-linux ./cmd/client
	mkdir -p "./package/etc/canary"
	cp .env ./package/etc/canary/.config
	mkdir -p "./package/usr/bin"
	cp ./bin/canary-linux ./package/usr/bin/canary-linux
	dpkg-deb --build ./package
	rm -f ./package/etc/canary/.config
	rm -f ./package/usr/bin/canary-linux
