name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Run tests
        run: go test ./...

      - name: Check test status
        run: exit ${{ steps.test.outcome == 'success' && 0 || 1 }}

      - name: Build application
        if: success()
        run: |
          bash build.sh

      - name: Deploy application
        if: success()
        run: |
          bash deploy.sh
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
